# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: "%env(APP_SECRET)%"
    trusted_proxies: "%env(TRUSTED_PROXIES)%"
    trusted_hosts: ["%env(TRUSTED_HOSTS)%"]
    csrf_protection: true
    trusted_headers:
        - "x-forwarded-for"
        - "x-forwarded-host"
        - "x-forwarded-proto"
        - "x-forwarded-prefix"
    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    exceptions:
        App\Entity\Dossier:
            status_code: 404
            log_level: "info"
        App\Entity\Utilisateur:
            status_code: 404
            log_level: "info"
        App\Entity\Evaluation:
            status_code: 404
            log_level: "info"
        App\Entity\Document:
            status_code: 404
            log_level: "info"
        App\Entity\Notification:
            status_code: 404
            log_level: "info"
        Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
            log_level: "info"
            status_code: 404
        Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException:
            log_level: "warning"
            status_code: 403

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
